"""
Brand and boilerplate for the generated note.

Kept out of the template so the report can be rebranded by editing one file.
The defaults are deliberately generic: the layout is modelled on a published
retail-research note, but the marks, registration details and disclosures here
are neutral placeholders, not any real firm's. Swap in your own before
distributing anything generated by this app.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Brand:
    name: str = "EQUIRESEARCH"
    tagline: str = "Independent Equity Insight"
    research_line: str = "Retail Equity Research"
    website: str = "www.example-research.com"

    rating_criteria: list[tuple[str, str, str, str]] = field(
        default_factory=lambda: [
            ("Buy", "Upside is above 10%", "Upside is above 15%", "Upside is above 20%"),
            ("Accumulate", "-", "Upside is between 10%-15%", "Upside is between 10%-20%"),
            ("Hold", "Upside is between 0%-10%", "Upside is between 0%-10%", "Upside is between 0%-10%"),
            ("Reduce/Sell", "Downside is more than 0%", "Downside is more than 0%", "Downside is more than 0%"),
            ("Not rated/Neutral", "-", "-", "-"),
        ]
    )

    rating_definitions: str = (
        "Buy: Acquire at the current market price (CMP), with the target mentioned in the note. "
        "Accumulate: Partial buying, or accumulate as the CMP dips in future. "
        "Hold: Hold the stock with the expected target mentioned in the note. "
        "Reduce: Reduce exposure to the stock due to limited upside. "
        "Sell: Exit the stock. "
        "Not rated/Neutral: The analyst has no investment opinion on the stock."
    )

    horizon_note: str = (
        "Recommendations are based on a 12-month horizon unless otherwise specified. "
        "Investment ratings are on an absolute positive/negative return basis. Because of "
        "volatility in the near to medium term, there could be a temporary mismatch to a "
        "rating; for reasons of valuation, return or lack of clarity we may revisit the "
        "rating at an appropriate time. A stock always carries the risk of being upgraded "
        "or downgraded."
    )

    disclaimer: list[str] = field(
        default_factory=lambda: [
            "This document is generated automatically from company-published material for "
            "demonstration and evaluation purposes. It is not investment advice, not a "
            "research report prepared by a registered research analyst, and not an offer or "
            "solicitation to buy or sell any security.",
            "Figures in this document are extracted from the supplied source document by an "
            "automated system and have not been verified by a human analyst. Cells shown as "
            "a dash were not available in the source. Any estimates or forward-looking "
            "statements are illustrative only.",
            "Standard warning: Investments in securities markets are subject to market "
            "risks. Read all related documents carefully before investing.",
            "Before distributing any report produced by this system, replace this section "
            "with your own firm's disclosures, regulatory registrations and analyst "
            "certification.",
        ]
    )


def load_brand() -> Brand:
    """Brand with per-deployment overrides from the environment."""
    return Brand(
        name=os.getenv("BRAND_NAME", Brand.name),
        tagline=os.getenv("BRAND_TAGLINE", Brand.tagline),
        research_line=os.getenv("BRAND_RESEARCH_LINE", Brand.research_line),
        website=os.getenv("BRAND_WEBSITE", Brand.website),
    )
